jobs:
    build:
        requires: [~pr, ~commit, ~sd@16:rollback]
        image: node:12
        steps:
            - echo: echo building
            - sleep: sleep 20s
            - meta: meta set version 1
    deploy-east:
        requires: [build]
        image: node:12
        steps:
            - echo: echo deploying east
            - meta: meta set east 2
    deploy-west:
        requires: [build]
        image: node:12
        steps:
            - echo: echo deploying west
            - meta: meta set west 3
    tests:
        requires: [deploy-west, deploy-east]
        image: node:12
        steps:
            - echo: echo testing wast and west
            - metas: |
                meta get version;
                meta get east;
                meta get west;
    rollback:
        image: node:12
        steps:
            - echo: echo rolling back version `meta get version`
